=================================
How to use 7-base_geometry module
=================================

Usage
=====

Importing class:
	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test Cases:
	>>> basegeo = BaseGeometry()
	>>> basegeo.integer_validator("int_1", 12)
	>>> basegeo.integer_validator("length", 100)

	>>> basegeo.area()
	Traceback (most recent call last):
	...
	Exception: area() is not implemented

	>>> basegeo.integer_validator("name", "gloria")
	Traceback (most recent call last):
	...
	TypeError: name must be an integer

	>>> basegeo.integer_validator("position", {5,10})
	Traceback (most recent call last):
	...
	TypeError: position must be an integer

	>>> basegeo.integer_validator("position", [1])
        Traceback (most recent call last):
        ...
        TypeError: position must be an integer

	>>> basegeo.integer_validator("position", float('nan'))
	Traceback (most recent call last):
	...
	TypeError: position must be an integer

	>>> basegeo.integer_validator("bignum",8399202993303094920293409240298409280958092747098280948230948209842098402984021098409832082084028)

	>>> basegeo.integer_validator()
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

	>>> basegeo.integer_validator("average")
	Traceback (most recent call last):
	...
	TypeError: integer_validator() missing 1 required positional argument: 'value'

	>>> basegeo.integer_validator("answer", True)
	Traceback (most recent call last):
	...
	TypeError: answer must be an integer

	>>> basegeo.integer_validator("answer", 2.4)
        Traceback (most recent call last):
        ...
        TypeError: answer must be an integer

	>>> basegeo.integer_validator("distance", -2)
        Traceback (most recent call last):
        ...
        ValueError: distance must be greater than 0

	>>> basegeo.integer_validator("distance", 0)
        Traceback (most recent call last):
        ...
        ValueError: distance must be greater than 0

	>>> basegeo.integer_validator("position", None)
        Traceback (most recent call last):
        ...
        TypeError: position must be an integer
